In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
 myarr = np.array([3,6,32,7], np.int8)

In [4]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [5]:
 myarr = np.array([3,6,32,7], np.int32)

In [6]:
myarr

array([ 3,  6, 32,  7], dtype=int32)

In [7]:
myarr[0]

3

In [76]:
 myarr = np.array([[3,6,32,7]], np.int8)
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [9]:
myarr[0,1]

6

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr.dtype

dtype('int8')

In [12]:
myarr[0,2]= 69

In [13]:
myarr

array([[ 3,  6, 69,  7]], dtype=int8)

**Array creation:Conversion from other Python structures**

In [14]:
 listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [15]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
listarray.dtype

dtype('int64')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [20]:
zeros= np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
rng = np.arange(15)

In [84]:
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [24]:
lspace = np.linspace(1,50,10)

In [25]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
lspace = np.linspace(1,4,4)

In [27]:
lspace

array([1., 2., 3., 4.])

In [28]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[1.94796250e-316, 0.00000000e+000, 6.90840951e-310,
        6.90840951e-310, 6.90840951e-310, 6.90840951e-310],
       [6.90840951e-310, 6.90840951e-310, 6.90840951e-310,
        6.90840951e-310, 6.90840951e-310, 6.90840951e-310],
       [6.90840951e-310, 6.90840951e-310, 6.90840951e-310,
        6.90840951e-310, 6.90840951e-310, 6.90840951e-310],
       [6.90840951e-310, 6.90840951e-310, 6.90840951e-310,
        6.90840951e-310, 6.90840951e-310, 6.90840951e-310]])

In [31]:
emp_like = np.empty_like(lspace)

In [32]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
ide = np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
ide.shape

(4, 4)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(x)

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
arr.sum(axis=0)

array([12,  8,  9])

In [43]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [44]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
arr.flat

In [46]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
arr.ndim

2

In [48]:
arr.size

9

In [49]:
arr.nbytes

72

In [50]:
one = np.array([1,3,4,634,2])

In [51]:
one.argmax()


3

In [52]:
one.argmin()

0

In [53]:
one.argsort()     # giving indices

array([0, 4, 1, 2, 3])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr.argmin()

8

In [56]:
arr.argmax(axis=0)

array([2, 1, 1])

In [57]:
arr.argmax(axis=1)

array([2, 2, 0])

In [58]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [59]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [60]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [62]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [63]:
ar = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [64]:
ar + arr

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [65]:
ar * arr

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [66]:
arr.sum()

29

In [67]:
arr.max()

7

In [68]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [69]:
np.count_nonzero(arr)

8

In [70]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [71]:
import sys

In [72]:
py_ar= [0,4,55,2]

In [73]:
np_ar= np.array(py_ar)

In [74]:
sys.getsizeof(1) * len(py_ar)

112

In [75]:
np_ar.itemsize*np_ar.size

32